### ISSUE TITLE
/app/wheels doesn't exist

### ISSUE THREAD

**Issue by drobilica** [miguelgrinberg/microflack_messages#6]
When running `docker build . -t mikroflak` i get this error 

```WARNING: Url '/app/wheels' is ignored. It is either a non-existing path or lacks a specific scheme.
ERROR: Could not find a version that satisfies the requirement MicroFlack-Common==0.3 (from -r /app/requirements.txt (line 22)) (from versions: none)
ERROR: No matching distribution found for MicroFlack-Common==0.3 (from -r /app/requirements.txt (line 22))
WARNING: Url '/app/wheels' is ignored. It is either a non-existing path or lacks a specific scheme.
The command '/bin/sh -c pip install --find-links /app/wheels -r /app/requirements.txt' returned a non-zero code: 1```

**Comment by miguelgrinberg** [comment]
Are you following the tutorial to run this project? It is fairly complex and has a lot of moving parts, the PyCon tutorial video is the ultimate reference.

**Comment by drobilica** [comment]
Unfortunately no  :) I was just browsing your repos and came across messaging app which seems very interesting . Where can i find your PyCon tutorial ?

**Comment by miguelgrinberg** [comment]
https://www.youtube.com/watch?v=nrzLdMWTRMM

**Comment by drobilica** [comment]
Thank you, i finished your microblog tutorial and i was crawing for more. Really looking forward for new stuff from you .

**Comment by miguelgrinberg** [comment]
Yeah, this tutorial is a very good follow up to the Mega-Tutorial. Enjoy!
